### ISSUE TITLE
Consider other file extensions

### ISSUE THREAD

**Issue by andrewmclagan** [atecarlos/webpack-babel-jest#11]
There exists cases with webpack where we import images:

`const successInfographic = require('./info-success.png');`

this will break with current implementation.

**Comment by atecarlos** [comment]
Hi @andrewmclagan that's true. I'm not against adding more extensions. However, in reference to the particular scenario you are describing, what I've done in my projects is to actually create a manual jest mock for the image. That way I can define a value for `successInfographic` and use that value when doing assertions in my test.

If we were to remove that line, wouldn't that break your test because `const successInfographic` would never be defined?
